---
pagetitle: "База данных коннекторов бежтинского языка"
---

# База данных коннекторов бежтинского языка
_З.М. Халилова_ (Институт языкознания РАН)

База данных создана при поддержке РНФ, проект № 22-18-00528 «Связь 
пропозициональных единиц в предложении и в тексте: семантика и пути 
грамматикализации».

База коннекторов бежтинского языка содержит информацию о семантике и 
синтаксических свойствах нефинитных форм и прочих средств связи клауз. База 
коннекторов бежтинского языка устроена следующим образом.

## Основная информация
В качестве лексического входа выступает морфологический показатель, частица или 
союз. 

## Семантика
Бежтинская база содержит информацию о принадлежности каждого коннектора к 
определенному семантическому полю: используется система, общая для всех баз 
проекта. Классификация по семантическому полю выполнена на основе данных 
грамматических описаний и уточнена с носителями языка. 

Для каждой единицы дается пример употребления. Часть примеров получена методом 
элицитации, также используются примеры из личного корпуса текстов автора и 
работы [Халилов 2020] (Халилов М.Ш На устах у бежтинцев: легенды, предания, 
сказки и рассказы. Махачкала, 2020). Все примеры были дополнительно проверены с 
носителями. Для каждого примера в отдельном поле приводится русский перевод.

## Синтаксис
Специфика бежтинского языка, как и других дагестанских языков, состоит в том, 
что полипредикативные конструкции чаще всего вводятся нефинитными формами 
глагола, а не подчинительными союзами. Сентенциальные актанты может возглавлять 
инфинитив, масдар, причастие или деепричастие. Единственной стратегией 
оформления относительных предложений является причастная стратегия. 
Обстоятельственные предложения могут возглавляться разнообразными формами, 
среди которых контекстуальное деепричастие и многочисленные специализированные 
деепричастия, формы условного и уступительного наклонения, инфинитив. 
Единственный вид зависимых предложений, возглавляемых финитными формами – 
конструкции, передающие чужую речь.

Морфосинтаксические параметры, релеватные для бежтинского материала:

- форма коннектора: морфологический показатель, частица или союз;
- термин, описывающий коннектор;
- семантическое поле и подзначение	;
- семантический комментарий;
- основной пример на употребление коннектора с глоссами и переводом;
- позиция зависимой клаузы в составе главной;
- примеры на вариативность позиции клаузы с глоссами и переводом;
- состав коннектора: элементарный или многокомпонентный;
- компоненты коннектора для составных коннекторов (показатели и термины, их 
  описывающие, напр. условное деепричастие _-da_ + аддитивная клитика _-na_);
- разрывность частей коннектора;
- позиция морфемы/союза: схематически представлена позиция морфемы в составе 
  нефинитной формы или союза/частицы в предложении;
- способность употребляться в независимом предложении с примером;
- присоединение аддитивной частицы;
- комментарии (с примерами).